### ISSUE TITLE
STAR parameters for multimappers

### ISSUE THREAD

**Issue by mlbendall** [nixonlab/DLBCL_HERV_atlas_GDC#1]
In order to use STAR output for Telescope we need to increase the number of valid alignments output for each read using `–outFilterMultimapNmax` and `–outAnchorMultimapNmax`. Try setting both to 200 and/or allow this to be configurable

**Comment by mlbendall** [comment]
I don't actually think they are using `outAnchorMultimapNmax` at least in STAR 2.7.9

**Comment by singhbhavya** [comment]
I'll put in `--outFilterMultimapNmax 200`. Manual says that if the max number of multiple alignments allowed for a read is exceeded, the read is considered unmapped

Could we use `--winAnchorMultimapNmax`?  It may be the replacement for `--outAnchorMultimapNmax`.  Manual says it is the max number of loci anchors are allowed to map to. [This issue here](https://github.com/alexdobin/STAR/issues/243) explains the function: "`--winAnchorMultimapNmax` is used to select anchor seeds - only seeds (exactly mapping portions of the read) that map to <= number of loci are considered anchors. Anchors define the genomic windows where a read mapping is attempted. For example, if you want to map read that map equally well to 100 loci, you would need to set --winAnchorMultimapNmax at least 100, though I would recommend double that number."

**Comment by singhbhavya** [comment]
Just to confirm, both values should be 200? According to [this issue here](https://github.com/mhammell-laboratory/TEtranscripts/issues/69) and [this issue](https://github.com/alexdobin/STAR/issues/243), if we are using `--outFilterMultimapNmax 200`, we should use `--winAnchorMultimapNmax 400` (also what was done [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3945725)). But I have also seen equal values (see [here](http://barcwiki.wi.mit.edu/wiki/SOPs/rna-seq-diff-expressions_TE)).
